### ISSUE TITLE
Dimensions in SI unit

### ISSUE THREAD

**Issue by bugeaud** [rkrenzler/ose-piping-workbench#4]
At this time, dimensions are setup in US customary units. Having OD/ID/Thk straight into SI unit would help to get consistent with the DN code plus would ease people to check that their exact pipes/fittings matches these mesurement (say Thk at least).

It would be nice to get the column "Schedule" renamed as "Grade" or "Norm" too. So we can also get the corresponding Presure grade from non US pipes, like PN10, PN16, PN25, etc. The 40 of the Schedule column could simply be then renamed to "SCHEDULE 40", and so on.

See https://www.jpcfrance.fr/bases-pratiques/filetages-et-raccordements/dimensions-des-tuyauteries-pvc-europe-vs-us/ for small pipe dimensions.

Having other standard size like DN140 and DN160 would be a nice too.

**Comment by rkrenzler** [comment]
OK, I will add support for Grade and Norm. Probably in the beginning of July.

**Comment by rkrenzler** [comment]
I used the US units, because historically this workbench was for mainly used by people from US. But one can also use normal 😁 units. You only need to append corresponding SI units to the values in the CSV files.

**Comment by rkrenzler** [comment]
SI is supported. It is possible to rename Schedule to Grade. It is even possible to use the both columns simultaneously, because they are not parts of calculations.

You only need to modify pipe.csv file. 
![different-pipes](https://user-images.githubusercontent.com/20125922/85946663-28b4ac80-b946-11ea-8bfa-a71d3165659e.png)

[pipe.zip](https://github.com/rkrenzler/ose-piping-workbench/files/4842175/pipe.zip)

I did no find a nice and simple way to add different measures to the default workbench files. If it is a problem, we can move the request to a separate issue and think about it.

**Comment by rkrenzler** [comment]
SI is supported. It is possible to rename _Schedule_ to _Grade_. It is even possible to use the both columns simultaneously because they are not used for calculations.

You only need to modify pipe.csv file. 
![different-pipes](https://user-images.githubusercontent.com/20125922/85946663-28b4ac80-b946-11ea-8bfa-a71d3165659e.png)

[pipe.zip](https://github.com/rkrenzler/ose-piping-workbench/files/4842175/pipe.zip)

I did no find a nice and simple way to add many different standads to the default workbench files. If it is a problem, we can move the request to a separate issue and think about it.

**Comment by bugeaud** [comment]
Thanks for the file. I will try to make a standard file for the usual international mesurement we find.

Let's have multiple default unit settings files in the module settings folder.

You could either add a settings anywhere to pick the preffered one (setting in another file or thry a UI in the preferences).

Doing so people could be free to create their own settings and pick them or change from time to time when needed.

At first launch you could guess from user Locale which unit would be prefered. If US Local = US Customary Units file will be used else the International Units file will be used by default. It would be up to the user to change this if required in the Preferences.

Rgs,
JB
